BUILD_DIR=build

all: 1-1

1-1: chapter1/listing1-1.cpp
	g++ -Wall -g chapter1/listing1-1.cpp -o ${BUILD_DIR}/$@

2-1: chapter2/listing2-1.cpp
	g++ -Wall -g chapter2/listing2-1.cpp -o ${BUILD_DIR}/$@

2-2: chapter2/listing2-2.cpp
	g++ -Wall -g chapter2/listing2-2.cpp -o ${BUILD_DIR}/$@

2-3: chapter2/listing2-3.cpp
	g++ -std=c++11 -Wall -g chapter2/listing2-3.cpp -o ${BUILD_DIR}/$@

2-6: chapter2/listing2-6.cpp
	g++ -std=c++11 -Wall -g chapter2/listing2-6.cpp -o ${BUILD_DIR}/$@

2-7: chapter2/listing2-7.cpp
	g++ -std=c++11 -Wall -g chapter2/listing2-7.cpp -o ${BUILD_DIR}/$@

2-8: chapter2/listing2-8.cpp
	g++ -std=c++11 -Wall -g chapter2/listing2-8.cpp -o ${BUILD_DIR}/$@

2-9: chapter2/listing2-9.cpp
	g++ -std=c++11 -Wall -g chapter2/listing2-9.cpp -o ${BUILD_DIR}/$@

3-1: chapter3/listing3-1.cpp
	g++ -std=c++11 -Wall -g chapter3/listing3-1.cpp -o ${BUILD_DIR}/$@

3-6: chapter3/listing3-6.cpp
	g++ -std=c++17 -Wall -g chapter3/listing3-6.cpp -o ${BUILD_DIR}/$@

3-8: chapter3/listing3-8.cpp
	g++ -std=c++11 -Wall -g chapter3/listing3-8.cpp -o ${BUILD_DIR}/$@